services:
    payment-service:
      urls:
        url: http://PaymentService/paymentControl/api/v1/doPayment
    order-service:
      urls:
        url: http://PaymentService/paymentControl/api/v1/doPayment
spring:
  config:
    import:
    - optional:configserver:http://localhost:9123

  datasource:
    username: root
    password: password
    url: jdbc:mysql://localhost:3306/newdb
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
server:
  port: 8084
eureka:
    client:
      register-with-eureka: true
      fetch-registry: true
    instance:
      hostname: localhost
management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
